### ISSUE TITLE
2x bastions overlapping = 2x placements to break

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/Bastion#16]
Tested this on civtest before the 1.8 stuff was put up (i.e. a few days ago), because everybody's always confused about it either way on reddit. When I put down 1 bastion it took X placements, when I put down 2 bastions it took 2X placements in the overlapping area.

I did not think this was unintended until ttk told me it was just now and said to put it on github.

**Comment by rourke750** [comment]
I thought that up until four bastions it was efficient to have
overlapping.  After four it the more you added it didn't help.

**Comment by rourke750** [comment]
Believe its just a config option.  Config value can be found here: https://github.com/Civcraft/Bastion/blob/master/Bastion/config.yml#L18 which is default which is why it would not be the same as civcraft.  Relevant code is here: https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/manager/BastionBlockManager.java#L73 .

**Comment by ttk2** [comment]
ah so it should be 1 on Civcraft?

**Comment by rourke750** [comment]
No civtest should be what ever civcraft says.  I believe it was four.  What
number does it say?

**Comment by spaceFountain** [comment]
If you wanted it to erode everything you should, set it less than 0. Any other number will decide how many Bastions that cover the area would get removed at once.

**Comment by rourke750** [comment]
Removed as in damaged correct?

**Comment by spaceFountain** [comment]
Wops I mistyped. It's indeed the number that get damaged or eroded as I called it in the code. It's a fairly simple function.

**Comment by ttk2** [comment]
ok so zero is damage all of them?

**Comment by rourke750** [comment]
Less than zero

**Comment by ttk2** [comment]
really -1? I hope that gets parsed right .
