### ISSUE TITLE
Bastion overlapping works

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Bastion#17]
It has been reported by multiple people that bastion overlapping currently works.

**Comment by rourke750** [comment]
Can you paste config pls.

**Comment by ttk2** [comment]
username:
  password:
  host: localhost
  database:
  port: 3306
  prefix:
  savesPerDay: 192
BastionBlock:
  material: SPONGE
  effectRadius: 10
  startScaleFactor: 100
  finalScaleFactor: 0.5
  warmUpTime: 172800000
  maxBreaksPerMinute: 30
  erosionRatePerDay: 0
  destroyOnRemove: false
  blocksToErode: 1
  EnderPearls:
    preventEnderPearl: true
    scaleFac: 1
    requireMaturity: true

removed username and database names as well as passwords obviously.

**Comment by spaceFountain** [comment]
So what exactly are you trying to do. If I recall to have it erode all the blocking bestions you need to set blocksToErode to less than 0.

**Comment by ttk2** [comment]
less than zero? as in any negative number?

**Comment by spaceFountain** [comment]
Yep see [this](https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/manager/BastionBlockManager.java#L67).

**Comment by spaceFountain** [comment]
It looks like it currently does not apply to teleporting though that's a pretty minor element in my mind.

**Comment by ttk2** [comment]
that's just strange, just -1?

**Comment by spaceFountain** [comment]
Assuming you want it to erode all the Bastions blocking a particular block being placed, yes. You could also just set it to a very high number as it normally describes how far down the list of blocking Bastions it will go, but it will be less efficient because it tries to randomly order the list in that case.

**Comment by rourke750** [comment]
I also recall having this conversation already.

**Comment by rourke750** [comment]
@ttk2 mfw https://github.com/Civcraft/Bastion/issues/16

**Comment by rourke750** [comment]
@ttk2 Is this fixed on the config?

**Comment by ttk2** [comment]
yup.
