### ISSUE TITLE
Bastion overrides Citadel's reinforcement creation

### ISSUE THREAD

**Issue by erocs** [Civcraft/Bastion#18]
Citadel's BlockPlaceEvent handler is firing before Bastion's so it creates the reinforcement (and deducts the reinforcement materials). Then Bastion comes in and cancels the event to prevent the block place.

Bastion needs its event handler moved lower in priority then Citadel's event handler. Alternatively, and probably better since Bastion has a hard dependency on Citadel, Citadel should detect the presence of Bastion and call it on a block place to let Bastion handle it if it needs to. Then Citadel can see the result of that and act accordingly.

**Comment by rourke750** [comment]
This is actually a citadel bug.  Citadel isnt checking if the block place was cancelled.

**Comment by rourke750** [comment]
https://github.com/Civcraft/Citadel/commit/7af0c33cdadf83bb106cec354584860ed976c4db#diff-35250cb092462f1ea9f47e16d8a7d5d5

**Comment by ttk2** [comment]
um so I guess Civmod core needs to go into testing so that we can get this onto Civtest?

**Comment by rourke750** [comment]
Its been mostly tested do to third party stuff (wew benefits of open
source) but I'm sure I can knock that all my self.  It would be really
obvious if something was broken as the plugin would not work properly.  But
yes all plugins need to go through testing when they gain the dependency
mostly to make sure they are configured correctly.

**Comment by ttk2** [comment]
what all needs updating on Civtest to sync up?
