### ISSUE TITLE
Bastions don't cover the level they're on

### ISSUE THREAD

**Issue by Eythx** [Civcraft/Bastion#21]
If I have several bastions at bedrock level it doesn't actually protect the level that they were placed. This means anyone can come into my bastion field and place bastions at bedrock level. After full maturity the illegally (for lack of a better word) placed bastions will conflict with the original bastions disallowing everyone from being able to build.

**Comment by ProgrammerDan** [comment]
This is intentional. Place IRO or DRO in a "floor" around the bastion to prevent the scenario you describe.
