### ISSUE TITLE
Broken ModeChange Command (Wrong usage of Integer.parseInt)

### ISSUE THREAD

**Issue by psygate** [Civcraft/Bastion#22]
The Integer.parseInt method cannot ever return null. The usage in package [isaac.bastion.commands.ModeChangeCommand#onCommand](https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/commands/ModeChangeCommand.java#L35) relies on Integer.parseInt returning null. Which it can't. [Integer.parseInt](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#parseInt-java.lang.String-) explicitly throws a NumberFormatException on failure.

Fix: Wrap usage of Integer.parseInt inside a try catch.

**Comment by ProgrammerDan** [comment]
since it's an admin command and not player-facing, assigning lower priority, but this is definitely not safe/correct code :)

**Comment by psygate** [comment]
It's _safe_ in the broadest meaning of the word. Yes, it does what it should on malformed input, but not exactly as expected by the author. The _surprise_ only shows up once someone wants to implement the else or else-if part of that if statement. They might rely on the preceding code and not realize that their code branch will always be dead.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/Bastion/commit/ab44585ff7cf8fce162b89be200de105b5f49b93
