### ISSUE TITLE
Odd usage of java.io.File

### ISSUE THREAD

**Issue by psygate** [Civcraft/Bastion#24]
[ConfigManager](https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/manager/ConfigManager.java#L45) uses String concatination instead of the [File(File parent, String child) constructor](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#File-java.io.File-java.lang.String-)

**Comment by Maxopoly** [comment]
Would changing this provide any advantage? It's obvious what it's doing and performance isn't an argument here either.

**Comment by ProgrammerDan** [comment]
Not really. The compiler will just convert it to a StringBuilder anyway, so efficiency isn't an argument.

It's more a semantic "correctness" -- so not a high priority. I could lower it.

**Comment by psygate** [comment]
It does some additional checks and path normalization, which can enhance the compatibility with different file systems than NTFS, FAT and Ext. It's not exactly the most urgend thing ever, but see here: http://www.docjar.com/html/api/java/io/File.java.html Line 289.

**Comment by Maxopoly** [comment]
This is a very weird approach anyway. Instead of hardcoding parsing from a file named "config.yml", and reimplementing a getter for every primitive, spigot's default config system should probably just be used in that class. The whole loading of the config and exception catching could be replaced with

```
Bastion plugin = Bastion.getPlugin();
plugin.saveDefaultConfig();
plugin.reloadConfig();
config = plugin.getConfig();
```

**Comment by ProgrammerDan** [comment]
Quite so; I see no reason not to correct it to use the Spigot loader system.
