### ISSUE TITLE
Possible memory leak without restart of the server

### ISSUE THREAD

**Issue by psygate** [Civcraft/Bastion#25]
[PlayerStates](https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/commands/PlayersStates.java) keeps the full Player object stored without apparent removal, marking all associated objects as "live" on a gc run. This is a bad idea, since Player might have loaded chunks associated and other "hidden" values that might start clogging up memory and making gc pauses longer and longer.

**Comment by ProgrammerDan** [comment]
Nice catch

**Comment by psygate** [comment]
I just over flew the classes and things... It might be removed at some point, but storing just the UUID of a player might be a better idea.

**Comment by ProgrammerDan** [comment]
Yeah, the pattern elsewhere is just to store UUID and look it up as needed.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/Bastion/pull/29
