### ISSUE TITLE
Unnecessary cancelled checks (Might be a false positive if spigot api is broken)

### ISSUE THREAD

**Issue by psygate** [Civcraft/Bastion#26]
[BastionListener)[https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/listeners/BastionListener.java] uses a lot of if cases to replace @EventHandler(ignoreCancelled = true). This is more a readability, double check issue.

**Comment by ProgrammerDan** [comment]
Probably the writer was unaware of the parameter on the annotation, not bad idea to "fix" however.

**Comment by spaceFountain** [comment]
Yep exactly, Apologize for the badly designed code and thanks for going around and looking at it. I'll just say in my defense this was literally the first large scale project I made.

**Comment by Maxopoly** [comment]
Actually it returns if the event is cancelled, so the annotation would have to be @EventHandler(ignoreCancelled = false), but this is already the default behavior. All the event.isCancelled ifs could be just removed and the behavior would be the same as the current one.

**Comment by ProgrammerDan** [comment]
Another inversion of logic on Bukkit's part? I thought ignoreCancelled = true would mirror the behavior of fail-fast is event is already cancelled. ignoreCancelled = false would mean the event trigger always fires even if the event is already cancelled, which would be the exact opposite of what's currently happening.

**Comment by psygate** [comment]
@ProgrammerDan @Maxopoly  Documentation says you need to set it to true to ignore cancelled events. https://github.com/SpigotMC/Spigot-API/blob/b3e065a2b11a6dd2590606600ae58ba08e8763f8/src/main/java/org/bukkit/event/EventHandler.java

**Comment by Maxopoly** [comment]
Yeah, I just read the same and realized my understand and everything related to that I wrote in the past is inversed. I thought ignoreCancelled=true meant that the method ignored the fact that the event is cancelled and runs anyway. 

So yeah, you are right.

**Comment by ProgrammerDan** [comment]
@psygate Thanks, that's what I remembered as well from reading the same API.

**Comment by psygate** [comment]
> Yeah, I just read the same and realized my understand and everything related to that I wrote in the past is inversed. I thought ignoreCancelled=true meant that the method ignored the fact that the event is cancelled and runs anyway.

> So yeah, you are right.

It's just really odd default behaviour. Why would I want cancelled events (expect in the case of a Monitor) to be passed to me anyways? The default EventHandler is not made to "uncancel" cancelled events anyways. It's just an odd design choice on spigots part.

**Comment by ProgrammerDan** [comment]
One of many imho, but pretty common for larger frameworks.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/Bastion/commit/1b1319d95c501f33af3c8f47d98eecf7b687e382
