### ISSUE TITLE
Throwing pearls at bastion fields should damage them more but not refund the pearl

### ISSUE THREAD

**Issue by TealNerd** [Civcraft/Bastion#32]
Currently I can throw a pearl 1800 times and break a bastion. This poses zero risk to me since I can be far away and there's no added cost because it gives the pearl back. I think I it would be better if the pearl did extra damage, requiring less pearls overall but at an added cost because it wouldn't refund the pearl to you. Obviously damage multiplier would have to be discussed and balanced but I think somewhere around ten damage per pearl would be good.

**Comment by IAPark** [comment]
https://github.com/Civcraft/Bastion/blob/master/Bastion/config.yml#L21 allows the relative damage of Ender pearls as compared to placing blocks to be controlled.

The pearl is put back in the inventory here https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/manager/EnderPearlManager.java#L410. (There's also some special code that gets called if a pearl actually lands inside the field in case something goes wrong with my other code).

Boy looking through it I can see some problems. Would anyone mind if I get a chance and I want to refactor some of it. I've done some of it before on a different account. I can provide proof of this if anyone wants, but I'd rather do it through PMs.

I have mixed feeling about the suggestion in general. Originally the pearls weren't given back, but people pointed out it might be hard for new players to understand. I feel like it's probably a decent idea, but probably the weight should be adjusted somewhat at least as compared to placing blocks (maybe both need to be more damaging)

**Comment by Maxopoly** [comment]
Feel free to fix whatever you want and to make a pull request for it.
