### ISSUE TITLE
block_midair=false still prevents people from teleporting out of a bastion field

### ISSUE THREAD

**Issue by IAPark** [Civcraft/Bastion#39]
I'm was reading the AMA about Bastions and it sounds like you want people to be able to pearl out of a field even if they are blocked. With the current source this won't happen. There's a check for where people are teleporting from so it should still get blocked.

https://github.com/Maxopoly/Bastion/blob/50a94e0f5759ac8025544f457903383e20277862/Bastion/src/isaac/bastion/manager/BastionBlockManager.java#L370-L394

**Comment by ProgrammerDan** [comment]
Addressed in pull #41 here: https://github.com/Civcraft/Bastion/pull/41/files#diff-e72c26d1525c8572356fba640341c545R396
