### ISSUE TITLE
Multiple bastion block support

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/Bastion#44]
[Based tealnerd has done the work & updated to 1.9](https://github.com/TealNerd/Bastion/commit/16aa5415f682286767a781abedf504b8c4cf2dd4?_pjax=%23js-repo-pjax-container)

@TealNerd

**Comment by TealNerd** [comment]
well the way i did it isn't perfect, definitely has some weirdness but i think it technically works?

honestly to really make this happen bastion needs a lot of work that im not really wanting to do right now, maybe in the future, maybe if diet is willing to pay me in something other than watermelon

**Comment by IAPark** [comment]
Do you want it so Bastions can be based on configurable structure?

**Comment by TealNerd** [comment]
No the way I wrote it just allows for multiple types of bastions which would use different types of blocks and have different properties

**Comment by TealNerd** [comment]
rude

**Comment by ProgrammerDan** [comment]
;P "completed by tealnerd who is bae"
