### ISSUE TITLE
Feature: Negative Decay or Regeneration

### ISSUE THREAD

**Issue by redmag3** [Civcraft/Bastion#50]
Is it possible to add a config option to have a bastion tick up per day that the group is active, sort of an opposite to the current citadel decay? So that damage will regen itself over time.

**Comment by ProgrammerDan** [comment]
Yeah, this is an explicit ask for Devoted.

**Comment by Maxopoly** [comment]
In that case it needs to be specced out better. Should it always heal? Only if the bastion wasnt damaged during the last X period of time? Only if a member (or someone with bypass perms) is online when the healing tick is done? 

Also whats the state of those different bastion types teal is doing, are those already on devoted? They are not in this repo.

**Comment by ProgrammerDan** [comment]
By configuration, per bastion type, heal damage per time period, regardless of other people online or not.

Other bastion types are on devoted repo. If it works I'll upstream.

**Comment by spaceFountain** [comment]
Can't you just set a negative decay?

**Comment by ProgrammerDan** [comment]
Worth a try

**Comment by Maxopoly** [comment]
I'd be surprised if it had proper handling of overhealing

**Comment by ProgrammerDan** [comment]
done...
