### ISSUE TITLE
Pistons can push 1 block into a bastion field (no further, though)

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/Bastion#53]
Presumably the intended behavior is not being able to push ANY blocks into a bastion field, but currently, if one is placed 2 blocks outside, then a cobble or whatever placed 1 block outside (i.e. the closest you can place it without being blocked), and then you activate the piston, it will push the block successfully into the field. If cycling with a second block, it won't.

**Comment by ProgrammerDan** [comment]
These are good issues, but this repository is woefully out of date. 

Please open issues on the maintained, active repository -- https://github.com/DevotedMC/Bastion/

**Comment by GavJenks** [comment]
k
