### ISSUE TITLE
Stacktrace on enabling bastion

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Bastion#7]
This occurs in all builds starting with 0.7

Java.lang.NoClassDefFoundError: 
vg/civcraft/mc/citadel/reinforcement/Reinforcement
        at 
isaac.bastion.storage.BastionBlockSet.<init>(BastionBlockSet.java:51) ~[?:?]
        at 
isaac.bastion.manager.BastionBlockManager.<init>(BastionBlockManager.java:51) 
~[?:?]
        at isaac.bastion.Bastion.onEnable(Bastion.java:37) ~[?:?]
        at 
org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) 
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at 
org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02de
c9b]
        at 
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02d
ec9b]
        at 
org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at 
org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec
9b]
        at 
net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at 
net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at 
net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at 
net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at 
net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at 
net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) 
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.ClassNotFoundException: 
vg.civcraft.mc.citadel.reinforcement.Reinforcement
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) 
~[?:1.7.0_65]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) 
~[?:1.7.0_65]
        at java.security.AccessController.doPrivileged(Native Method) 
~[?:1.7.0_65]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) 
~[?:1.7.0_65]
        at 
org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) 
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02de
c9b]
        at 
org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) 
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec
9b]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) 
~[?:1.7.0_65]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) 
~[?:1.7.0_65]
        ... 14 more

**Comment by rourke750** [comment]
Please tell me you aren't putting these on civcraft.

**Comment by drjawa** [comment]
This was on civtest
