### ISSUE TITLE
Bastions not breaking at right rate

### ISSUE THREAD

**Issue by ribagi** [Civcraft/Bastion#8]
Last night a group attacked Titan, and while breaking their bastions with 20-40 people by block placements it looks like the time it took to break the bastions did not equal the amount of time one would expect. Did the fix to for groups to break bastions faster then single people ever get tested?

**Comment by ttk2** [comment]
it was tested, it worked just fine, but my guess is that this was the 21
day bug that was just fixed and is not yet out of testing

**Comment by rourke750** [comment]
Closed for now, reopen if occurs in future
