### ISSUE TITLE
Confirm bug with bastions taking too long to break

### ISSUE THREAD

**Issue by rourke750** [Civcraft/Bastion#9]
Players report that during high lag time bastions take longer to break.  This should not be the case as Bastions look at the current system time and not the amount of ticks that have past.

Possible ways to debug this are when pvp is happening and players are trying to break bastions by placing blocks use /bsi to check and make sure that bastions are infact being damaged correctly.  Then check the time to when high tick usage to see if similar or different behavior.

**Comment by ttk2** [comment]
well lag is common enough that this should be easy to check

**Comment by spaceFountain** [comment]
To do this properly we need someone with the Bastion.dev permission. So they can see exactly how much damage is being done each time. The only way I can think that lag would cause Bastions to break slower is if the server is counting less than 1 block placement every 2 seconds.

**Comment by drjawa** [comment]
I can hope on and test sometime Sunday.

**Comment by Xavter** [comment]
I can maybe do this on saturday when lag is abundant.

**Comment by ttk2** [comment]
closing this as it has not been reported in some time.
